// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/mkaiho/go-ws-sample/usecase/port"
	mock "github.com/stretchr/testify/mock"
)

// RoomsWriter is an autogenerated mock type for the RoomsWriter type
type RoomsWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, input
func (_m *RoomsWriter) Create(ctx context.Context, input *port.CreateRoomInput) (*port.CreateRoomOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *port.CreateRoomOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *port.CreateRoomInput) (*port.CreateRoomOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *port.CreateRoomInput) *port.CreateRoomOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*port.CreateRoomOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *port.CreateRoomInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRoomsWriter creates a new instance of RoomsWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomsWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomsWriter {
	mock := &RoomsWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
